name: Continuous Integration

on: [pull_request, push]
  branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.11.0

      - name: Install dependencies
        run: npm install

      - name: Run Compile TSC
        run: tsc

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Run Lint
        run: npm run lint
